from backend.app.prompts.risk_prompt import RISK_ASSESSMENT_SYSTEM_PROMPT, RISK_ASSESSMENT_USER_PROMPT
from backend.app.prompts.analysis_prompt import SENSOR_ANALYSIS_SYSTEM_PROMPT, SENSOR_ANALYSIS_USER_PROMPT
from backend.app.prompts.draft_prompt import DRAFT_RECOMMENDATION_SYSTEM_PROMPT, DRAFT_RECOMMENDATION_USER_PROMPT
from backend.app.prompts.review_prompt import REVIEW_SYSTEM_PROMPT, REVIEW_USER_PROMPT

__all__ = [
    "RISK_ASSESSMENT_SYSTEM_PROMPT",
    "RISK_ASSESSMENT_USER_PROMPT",
    "SENSOR_ANALYSIS_SYSTEM_PROMPT",
    "SENSOR_ANALYSIS_USER_PROMPT",
    "DRAFT_RECOMMENDATION_SYSTEM_PROMPT",
    "DRAFT_RECOMMENDATION_USER_PROMPT",
    "REVIEW_SYSTEM_PROMPT",
    "REVIEW_USER_PROMPT",
]
